### ISSUE TITLE
Where's the code?

### ISSUE THREAD

**Issue by mattneub** [felipeflorencio/SkyBar#2]
Isn't the point of GitHub to be open source? It's not a distribution mechanism for binaries (though it can be used for that as well). Could you please post the source code as well? Thanks.

**Comment by felipeflorencio** [comment]
Actually Github is a tool to manage your source-code, binary or not, the reason why I choose here is that people can simply check versions when a new update come.

I'm using github to distribute my project, this doesn't mean that need to be source code, the same way you can host your page using github.

For now, the source will remain close, unless someone "buy me a coffee" that makes me happy to share the source code ;)
